/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AddProductPropertyDto
 */
export interface AddProductPropertyDto {

    /**
     * @type {string}
     * @memberof AddProductPropertyDto
     */
    title?: string | null;

    /**
     * @type {string}
     * @memberof AddProductPropertyDto
     */
    value?: string | null;

    /**
     * @type {boolean}
     * @memberof AddProductPropertyDto
     */
    isFilter?: boolean;
}
