/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AddNewBrandDto
 */
export interface AddNewBrandDto {

    /**
     * @type {string}
     * @memberof AddNewBrandDto
     */
    persianName: string;

    /**
     * @type {string}
     * @memberof AddNewBrandDto
     */
    englishName: string;

    /**
     * @type {number}
     * @memberof AddNewBrandDto
     */
    multimediaDetailId?: number | null;

    /**
     * @type {string}
     * @memberof AddNewBrandDto
     */
    description?: string | null;
}
