/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AddResellerDto
 */
export interface AddResellerDto {

    /**
     * @type {string}
     * @memberof AddResellerDto
     */
    storeName: string;

    /**
     * @type {string}
     * @memberof AddResellerDto
     */
    storeAddress?: string | null;

    /**
     * @type {string}
     * @memberof AddResellerDto
     */
    nationalCode?: string | null;

    /**
     * @type {string}
     * @memberof AddResellerDto
     */
    mobileNumber?: string | null;

    /**
     * @type {string}
     * @memberof AddResellerDto
     */
    telephoneNumber?: string | null;
}
