/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FilterProductDto
 */
export interface FilterProductDto {

    /**
     * @type {Array<number>}
     * @memberof FilterProductDto
     */
    productTypeIds?: Array<number> | null;

    /**
     * @type {string}
     * @memberof FilterProductDto
     */
    phrase?: string | null;

    /**
     * @type {number}
     * @memberof FilterProductDto
     */
    pageIndex: number;

    /**
     * @type {number}
     * @memberof FilterProductDto
     */
    pageSize: number;
}
