/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OrderStatus } from './order-status';
import { PaymentStatus } from './payment-status';
 /**
 * 
 *
 * @export
 * @interface FilterFactorDto
 */
export interface FilterFactorDto {

    /**
     * @type {string}
     * @memberof FilterFactorDto
     */
    phrase?: string | null;

    /**
     * @type {OrderStatus}
     * @memberof FilterFactorDto
     */
    orderStatusId: OrderStatus;

    /**
     * @type {PaymentStatus}
     * @memberof FilterFactorDto
     */
    paymentStatusId: PaymentStatus;

    /**
     * @type {number}
     * @memberof FilterFactorDto
     */
    pageIndex: number;

    /**
     * @type {number}
     * @memberof FilterFactorDto
     */
    pageSize: number;

    /**
     * @type {Date}
     * @memberof FilterFactorDto
     */
    fromCreationDate?: Date | null;

    /**
     * @type {Date}
     * @memberof FilterFactorDto
     */
    toCreationDate?: Date | null;
}
