/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetProductAndPriceDom } from './get-product-and-price-dom';
import { ItemOrderStatus } from './item-order-status';
 /**
 * 
 *
 * @export
 * @interface GetFactorItemDom
 */
export interface GetFactorItemDom {

    /**
     * @type {number}
     * @memberof GetFactorItemDom
     */
    id?: number;

    /**
     * @type {number}
     * @memberof GetFactorItemDom
     */
    productAndPropertyPriceId?: number;

    /**
     * @type {string}
     * @memberof GetFactorItemDom
     */
    name?: string | null;

    /**
     * @type {number}
     * @memberof GetFactorItemDom
     */
    totalCount?: number;

    /**
     * @type {number}
     * @memberof GetFactorItemDom
     */
    b2BPrice?: number;

    /**
     * @type {number}
     * @memberof GetFactorItemDom
     */
    b2CPrice?: number;

    /**
     * @type {number}
     * @memberof GetFactorItemDom
     */
    specialPrice?: number;

    /**
     * @type {ItemOrderStatus}
     * @memberof GetFactorItemDom
     */
    itemOrderStatusId?: ItemOrderStatus;

    /**
     * @type {GetProductAndPriceDom}
     * @memberof GetFactorItemDom
     */
    productInfo?: GetProductAndPriceDom;
}
