/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FactorType } from './factor-type';
import { GetAddressInfoDom } from './get-address-info-dom';
import { GetCustomerDom } from './get-customer-dom';
import { GetFactorItemDom } from './get-factor-item-dom';
import { OrderStatus } from './order-status';
import { PaymentStatus } from './payment-status';
import { PriceType } from './price-type';
 /**
 * 
 *
 * @export
 * @interface GetFactorDom
 */
export interface GetFactorDom {

    /**
     * @type {number}
     * @memberof GetFactorDom
     */
    id?: number;

    /**
     * @type {number}
     * @memberof GetFactorDom
     */
    creatorUserId?: number | null;

    /**
     * @type {FactorType}
     * @memberof GetFactorDom
     */
    factorTypeId?: FactorType;

    /**
     * @type {PriceType}
     * @memberof GetFactorDom
     */
    priceTypeId?: PriceType;

    /**
     * @type {number}
     * @memberof GetFactorDom
     */
    totalPrice?: number;

    /**
     * @type {string}
     * @memberof GetFactorDom
     */
    description?: string | null;

    /**
     * @type {number}
     * @memberof GetFactorDom
     */
    factorCode?: number;

    /**
     * @type {Date}
     * @memberof GetFactorDom
     */
    creationTime?: Date;

    /**
     * @type {PaymentStatus}
     * @memberof GetFactorDom
     */
    paymentStatusId?: PaymentStatus;

    /**
     * @type {OrderStatus}
     * @memberof GetFactorDom
     */
    orderStatusId?: OrderStatus;

    /**
     * @type {boolean}
     * @memberof GetFactorDom
     */
    isTransactionOk?: boolean;

    /**
     * @type {GetCustomerDom}
     * @memberof GetFactorDom
     */
    customerInfo?: GetCustomerDom;

    /**
     * @type {GetAddressInfoDom}
     * @memberof GetFactorDom
     */
    addressInfo?: GetAddressInfoDom;

    /**
     * @type {Array<GetFactorItemDom>}
     * @memberof GetFactorDom
     */
    itemsList?: Array<GetFactorItemDom> | null;
}
