/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetResellerDom } from './get-reseller-dom';
import { SendType } from './send-type';
 /**
 * 
 *
 * @export
 * @interface GetProductAndPriceDom
 */
export interface GetProductAndPriceDom {

    /**
     * @type {number}
     * @memberof GetProductAndPriceDom
     */
    id?: number;

    /**
     * @type {string}
     * @memberof GetProductAndPriceDom
     */
    warranty?: string | null;

    /**
     * @type {SendType}
     * @memberof GetProductAndPriceDom
     */
    sendTypeId?: SendType;

    /**
     * @type {GetResellerDom}
     * @memberof GetProductAndPriceDom
     */
    resellerInfo?: GetResellerDom;
}
