/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetAddressInfoDom
 */
export interface GetAddressInfoDom {

    /**
     * @type {number}
     * @memberof GetAddressInfoDom
     */
    id?: number;

    /**
     * @type {string}
     * @memberof GetAddressInfoDom
     */
    province?: string | null;

    /**
     * @type {string}
     * @memberof GetAddressInfoDom
     */
    city?: string | null;

    /**
     * @type {string}
     * @memberof GetAddressInfoDom
     */
    address?: string | null;

    /**
     * @type {string}
     * @memberof GetAddressInfoDom
     */
    postalCode?: string | null;

    /**
     * @type {string}
     * @memberof GetAddressInfoDom
     */
    unit?: string | null;

    /**
     * @type {string}
     * @memberof GetAddressInfoDom
     */
    plaque?: string | null;

    /**
     * @type {string}
     * @memberof GetAddressInfoDom
     */
    latitude?: string | null;

    /**
     * @type {string}
     * @memberof GetAddressInfoDom
     */
    longitude?: string | null;

    /**
     * @type {string}
     * @memberof GetAddressInfoDom
     */
    recipientName?: string | null;

    /**
     * @type {string}
     * @memberof GetAddressInfoDom
     */
    recipientSurname?: string | null;

    /**
     * @type {string}
     * @memberof GetAddressInfoDom
     */
    recipientMobileNumber?: string | null;

    /**
     * @type {boolean}
     * @memberof GetAddressInfoDom
     */
    isRecipientMySelf?: boolean;
}
