/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetCustomerDom
 */
export interface GetCustomerDom {

    /**
     * @type {number}
     * @memberof GetCustomerDom
     */
    id?: number;

    /**
     * @type {string}
     * @memberof GetCustomerDom
     */
    firstName?: string | null;

    /**
     * @type {string}
     * @memberof GetCustomerDom
     */
    lastName?: string | null;

    /**
     * @type {string}
     * @memberof GetCustomerDom
     */
    fullName?: string | null;

    /**
     * @type {string}
     * @memberof GetCustomerDom
     */
    mobileNumber?: string | null;
}
