/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetMediaDetailDto
 */
export interface GetMediaDetailDto {

    /**
     * @type {number}
     * @memberof GetMediaDetailDto
     */
    multimediaDetailId: number;

    /**
     * @type {boolean}
     * @memberof GetMediaDetailDto
     */
    isMain?: boolean;
}
