/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MediaCategory } from './media-category';
import { MediaSize } from './media-size';
import { MediaType } from './media-type';
import { MultimediaInfo } from './multimedia-info';
 /**
 * 
 *
 * @export
 * @interface MultimediaCapabilities
 */
export interface MultimediaCapabilities {

    /**
     * @type {number}
     * @memberof MultimediaCapabilities
     */
    multimediaDetailId?: number;

    /**
     * @type {boolean}
     * @memberof MultimediaCapabilities
     */
    isMain?: boolean;

    /**
     * @type {MediaType}
     * @memberof MultimediaCapabilities
     */
    mediaTypeId?: MediaType;

    /**
     * @type {MediaSize}
     * @memberof MultimediaCapabilities
     */
    mediaSizeId?: MediaSize;

    /**
     * @type {string}
     * @memberof MultimediaCapabilities
     */
    url?: string | null;

    /**
     * @type {string}
     * @memberof MultimediaCapabilities
     */
    caption?: string | null;

    /**
     * @type {string}
     * @memberof MultimediaCapabilities
     */
    fileAddress?: string | null;

    /**
     * @type {MultimediaInfo}
     * @memberof MultimediaCapabilities
     */
    mediaInfo?: MultimediaInfo;

    /**
     * @type {MediaCategory}
     * @memberof MultimediaCapabilities
     */
    mediaCategoryId?: MediaCategory;
}
