/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SendType } from './send-type';
 /**
 * 
 *
 * @export
 * @interface UpdateNewProdAndPropPriceDto
 */
export interface UpdateNewProdAndPropPriceDto {

    /**
     * @type {number}
     * @memberof UpdateNewProdAndPropPriceDto
     */
    id?: number;

    /**
     * @type {number}
     * @memberof UpdateNewProdAndPropPriceDto
     */
    specialSaleId?: number | null;

    /**
     * @type {number}
     * @memberof UpdateNewProdAndPropPriceDto
     */
    specialPrice?: number;

    /**
     * @type {number}
     * @memberof UpdateNewProdAndPropPriceDto
     */
    purchasePrice?: number;

    /**
     * @type {number}
     * @memberof UpdateNewProdAndPropPriceDto
     */
    b2BPrice?: number;

    /**
     * @type {number}
     * @memberof UpdateNewProdAndPropPriceDto
     */
    b2CPrice?: number;

    /**
     * @type {number}
     * @memberof UpdateNewProdAndPropPriceDto
     */
    remainingCount?: number;

    /**
     * @type {Date}
     * @memberof UpdateNewProdAndPropPriceDto
     */
    startSpecialSaleDate?: Date | null;

    /**
     * @type {Date}
     * @memberof UpdateNewProdAndPropPriceDto
     */
    endSpecialSaleDate?: Date | null;

    /**
     * @type {string}
     * @memberof UpdateNewProdAndPropPriceDto
     */
    warranty?: string | null;

    /**
     * @type {SendType}
     * @memberof UpdateNewProdAndPropPriceDto
     */
    sendTypeId?: SendType;
}
