/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateProductSpecificationDto
 */
export interface UpdateProductSpecificationDto {

    /**
     * @type {number}
     * @memberof UpdateProductSpecificationDto
     */
    id: number;

    /**
     * @type {string}
     * @memberof UpdateProductSpecificationDto
     */
    title: string;

    /**
     * @type {string}
     * @memberof UpdateProductSpecificationDto
     */
    value: string;

    /**
     * @type {boolean}
     * @memberof UpdateProductSpecificationDto
     */
    isFilter: boolean;
}
