/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetMediaDetailInfoDom } from './get-media-detail-info-dom';
 /**
 * 
 *
 * @export
 * @interface UpdateProductDto
 */
export interface UpdateProductDto {

    /**
     * @type {number}
     * @memberof UpdateProductDto
     */
    id: number;

    /**
     * @type {string}
     * @memberof UpdateProductDto
     */
    persianName: string;

    /**
     * @type {string}
     * @memberof UpdateProductDto
     */
    englishName?: string | null;

    /**
     * @type {string}
     * @memberof UpdateProductDto
     */
    barCode: string;

    /**
     * @type {string}
     * @memberof UpdateProductDto
     */
    introduction?: string | null;

    /**
     * @type {string}
     * @memberof UpdateProductDto
     */
    expertCheck?: string | null;

    /**
     * @type {number}
     * @memberof UpdateProductDto
     */
    productTypeId: number;

    /**
     * @type {number}
     * @memberof UpdateProductDto
     */
    brandId: number;

    /**
     * @type {Array<GetMediaDetailInfoDom>}
     * @memberof UpdateProductDto
     */
    multimedia?: Array<GetMediaDetailInfoDom> | null;

    /**
     * @type {Array<number>}
     * @memberof UpdateProductDto
     */
    productSpecificationIds?: Array<number> | null;
}
