/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GenderType } from './gender-type';
 /**
 * 
 *
 * @export
 * @interface UpdateCustomerDto
 */
export interface UpdateCustomerDto {

    /**
     * @type {number}
     * @memberof UpdateCustomerDto
     */
    customerId: number;

    /**
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    firstName?: string | null;

    /**
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    lastName: string;

    /**
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    mobileNumber: string;

    /**
     * @type {GenderType}
     * @memberof UpdateCustomerDto
     */
    genderType: GenderType;

    /**
     * @type {Date}
     * @memberof UpdateCustomerDto
     */
    birthDate?: Date | null;
}
