/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateMenuDto
 */
export interface UpdateMenuDto {

    /**
     * @type {number}
     * @memberof UpdateMenuDto
     */
    id: number;

    /**
     * @type {string}
     * @memberof UpdateMenuDto
     */
    persianName: string;

    /**
     * @type {string}
     * @memberof UpdateMenuDto
     */
    englishName: string;

    /**
     * @type {string}
     * @memberof UpdateMenuDto
     */
    url: string;

    /**
     * @type {string}
     * @memberof UpdateMenuDto
     */
    icon?: string | null;

    /**
     * @type {number}
     * @memberof UpdateMenuDto
     */
    parentId?: number | null;
}
