/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { FilterFactorDto } from '../models';
import { FilterFactorsResultInfo } from '../models';
import { GetFactorAndItemDto } from '../models';
import { GetFactorDom } from '../models';
import { ResultDto } from '../models';
/**
 * FactorApi - axios parameter creator
 * @export
 */
export const FactorApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {FilterFactorDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServicesAppFactorFilterForCurrentResellerPost: async (body?: FilterFactorDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/services/app/Factor/FilterForCurrentReseller`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServicesAppFactorGetByIdInAdminPanelGet: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiServicesAppFactorGetByIdInAdminPanelGet.');
            }
            const localVarPath = `/api/services/app/Factor/GetByIdInAdminPanel`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['Id'] = id;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {GetFactorAndItemDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServicesAppFactorUpdateItemStatusPut: async (body?: GetFactorAndItemDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/services/app/Factor/UpdateItemStatus`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FactorApi - functional programming interface
 * @export
 */
export const FactorApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {FilterFactorDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppFactorFilterForCurrentResellerPost(body?: FilterFactorDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<FilterFactorsResultInfo>>> {
            const localVarAxiosArgs = await FactorApiAxiosParamCreator(configuration).apiServicesAppFactorFilterForCurrentResellerPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppFactorGetByIdInAdminPanelGet(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GetFactorDom>>> {
            const localVarAxiosArgs = await FactorApiAxiosParamCreator(configuration).apiServicesAppFactorGetByIdInAdminPanelGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {GetFactorAndItemDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppFactorUpdateItemStatusPut(body?: GetFactorAndItemDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ResultDto>>> {
            const localVarAxiosArgs = await FactorApiAxiosParamCreator(configuration).apiServicesAppFactorUpdateItemStatusPut(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * FactorApi - factory interface
 * @export
 */
export const FactorApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {FilterFactorDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppFactorFilterForCurrentResellerPost(body?: FilterFactorDto, options?: AxiosRequestConfig): Promise<AxiosResponse<FilterFactorsResultInfo>> {
            return FactorApiFp(configuration).apiServicesAppFactorFilterForCurrentResellerPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppFactorGetByIdInAdminPanelGet(id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<GetFactorDom>> {
            return FactorApiFp(configuration).apiServicesAppFactorGetByIdInAdminPanelGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GetFactorAndItemDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppFactorUpdateItemStatusPut(body?: GetFactorAndItemDto, options?: AxiosRequestConfig): Promise<AxiosResponse<ResultDto>> {
            return FactorApiFp(configuration).apiServicesAppFactorUpdateItemStatusPut(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FactorApi - object-oriented interface
 * @export
 * @class FactorApi
 * @extends {BaseAPI}
 */
export class FactorApi extends BaseAPI {
    /**
     * 
     * @param {FilterFactorDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FactorApi
     */
    public async apiServicesAppFactorFilterForCurrentResellerPost(body?: FilterFactorDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<FilterFactorsResultInfo>> {
        return FactorApiFp(this.configuration).apiServicesAppFactorFilterForCurrentResellerPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FactorApi
     */
    public async apiServicesAppFactorGetByIdInAdminPanelGet(id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<GetFactorDom>> {
        return FactorApiFp(this.configuration).apiServicesAppFactorGetByIdInAdminPanelGet(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {GetFactorAndItemDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FactorApi
     */
    public async apiServicesAppFactorUpdateItemStatusPut(body?: GetFactorAndItemDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<ResultDto>> {
        return FactorApiFp(this.configuration).apiServicesAppFactorUpdateItemStatusPut(body, options).then((request) => request(this.axios, this.basePath));
    }
}
