/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { FilterMultimediaDto } from '../models';
import { GetMultimediaListResult } from '../models';
import { ResultDto } from '../models';
/**
 * MultimediaApi - axios parameter creator
 * @export
 */
export const MultimediaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} multimediaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServicesAppMultimediaDeleteDelete: async (multimediaId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'multimediaId' is not null or undefined
            if (multimediaId === null || multimediaId === undefined) {
                throw new RequiredError('multimediaId','Required parameter multimediaId was null or undefined when calling apiServicesAppMultimediaDeleteDelete.');
            }
            const localVarPath = `/api/services/app/Multimedia/Delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (multimediaId !== undefined) {
                localVarQueryParameter['MultimediaId'] = multimediaId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {FilterMultimediaDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServicesAppMultimediaFilterPost: async (body?: FilterMultimediaDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/services/app/Multimedia/Filter`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Array<Blob>} [files] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServicesAppMultimediaUploadMultiFilesPostForm: async (files?: Array<Blob>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/services/app/Multimedia/UploadMultiFiles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();

            if (files) {
                files.forEach((element) => {
                    localVarFormParams.append('Files', element as any);
                })
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MultimediaApi - functional programming interface
 * @export
 */
export const MultimediaApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} multimediaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppMultimediaDeleteDelete(multimediaId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ResultDto>>> {
            const localVarAxiosArgs = await MultimediaApiAxiosParamCreator(configuration).apiServicesAppMultimediaDeleteDelete(multimediaId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {FilterMultimediaDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppMultimediaFilterPost(body?: FilterMultimediaDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GetMultimediaListResult>>> {
            const localVarAxiosArgs = await MultimediaApiAxiosParamCreator(configuration).apiServicesAppMultimediaFilterPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {Array<Blob>} [files] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppMultimediaUploadMultiFilesPostForm(files?: Array<Blob>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ResultDto>>> {
            const localVarAxiosArgs = await MultimediaApiAxiosParamCreator(configuration).apiServicesAppMultimediaUploadMultiFilesPostForm(files, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MultimediaApi - factory interface
 * @export
 */
export const MultimediaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {number} multimediaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppMultimediaDeleteDelete(multimediaId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<ResultDto>> {
            return MultimediaApiFp(configuration).apiServicesAppMultimediaDeleteDelete(multimediaId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {FilterMultimediaDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppMultimediaFilterPost(body?: FilterMultimediaDto, options?: AxiosRequestConfig): Promise<AxiosResponse<GetMultimediaListResult>> {
            return MultimediaApiFp(configuration).apiServicesAppMultimediaFilterPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {Array<Blob>} [files] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppMultimediaUploadMultiFilesPostForm(files?: Array<Blob>, options?: AxiosRequestConfig): Promise<AxiosResponse<ResultDto>> {
            return MultimediaApiFp(configuration).apiServicesAppMultimediaUploadMultiFilesPostForm(files, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MultimediaApi - object-oriented interface
 * @export
 * @class MultimediaApi
 * @extends {BaseAPI}
 */
export class MultimediaApi extends BaseAPI {
    /**
     * 
     * @param {number} multimediaId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MultimediaApi
     */
    public async apiServicesAppMultimediaDeleteDelete(multimediaId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<ResultDto>> {
        return MultimediaApiFp(this.configuration).apiServicesAppMultimediaDeleteDelete(multimediaId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {FilterMultimediaDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MultimediaApi
     */
    public async apiServicesAppMultimediaFilterPost(body?: FilterMultimediaDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<GetMultimediaListResult>> {
        return MultimediaApiFp(this.configuration).apiServicesAppMultimediaFilterPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {Array<Blob>} [files] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MultimediaApi
     */
    public async apiServicesAppMultimediaUploadMultiFilesPostForm(files?: Array<Blob>, options?: AxiosRequestConfig) : Promise<AxiosResponse<ResultDto>> {
        return MultimediaApiFp(this.configuration).apiServicesAppMultimediaUploadMultiFilesPostForm(files, options).then((request) => request(this.axios, this.basePath));
    }
}
