/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AddProductSpecificationsDto } from '../models';
import { FilterProductSpecificationDto } from '../models';
import { GetAllSpecificationsResultInfo } from '../models';
import { ProductSpecificationsFilterResultInfo } from '../models';
import { ResultDto } from '../models';
import { UpdateProductSpecificationDto } from '../models';
/**
 * ProductSpecificationApi - axios parameter creator
 * @export
 */
export const ProductSpecificationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {AddProductSpecificationsDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServicesAppProductSpecificationAddBulkPost: async (body?: AddProductSpecificationsDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/services/app/ProductSpecification/AddBulk`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {FilterProductSpecificationDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServicesAppProductSpecificationFilterPost: async (body?: FilterProductSpecificationDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/services/app/ProductSpecification/Filter`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServicesAppProductSpecificationGetAllGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/services/app/ProductSpecification/GetAll`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateProductSpecificationDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServicesAppProductSpecificationUpdatePut: async (body?: UpdateProductSpecificationDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/services/app/ProductSpecification/Update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProductSpecificationApi - functional programming interface
 * @export
 */
export const ProductSpecificationApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {AddProductSpecificationsDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppProductSpecificationAddBulkPost(body?: AddProductSpecificationsDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ResultDto>>> {
            const localVarAxiosArgs = await ProductSpecificationApiAxiosParamCreator(configuration).apiServicesAppProductSpecificationAddBulkPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {FilterProductSpecificationDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppProductSpecificationFilterPost(body?: FilterProductSpecificationDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ProductSpecificationsFilterResultInfo>>> {
            const localVarAxiosArgs = await ProductSpecificationApiAxiosParamCreator(configuration).apiServicesAppProductSpecificationFilterPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppProductSpecificationGetAllGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GetAllSpecificationsResultInfo>>> {
            const localVarAxiosArgs = await ProductSpecificationApiAxiosParamCreator(configuration).apiServicesAppProductSpecificationGetAllGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {UpdateProductSpecificationDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppProductSpecificationUpdatePut(body?: UpdateProductSpecificationDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ResultDto>>> {
            const localVarAxiosArgs = await ProductSpecificationApiAxiosParamCreator(configuration).apiServicesAppProductSpecificationUpdatePut(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ProductSpecificationApi - factory interface
 * @export
 */
export const ProductSpecificationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {AddProductSpecificationsDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppProductSpecificationAddBulkPost(body?: AddProductSpecificationsDto, options?: AxiosRequestConfig): Promise<AxiosResponse<ResultDto>> {
            return ProductSpecificationApiFp(configuration).apiServicesAppProductSpecificationAddBulkPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {FilterProductSpecificationDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppProductSpecificationFilterPost(body?: FilterProductSpecificationDto, options?: AxiosRequestConfig): Promise<AxiosResponse<ProductSpecificationsFilterResultInfo>> {
            return ProductSpecificationApiFp(configuration).apiServicesAppProductSpecificationFilterPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppProductSpecificationGetAllGet(options?: AxiosRequestConfig): Promise<AxiosResponse<GetAllSpecificationsResultInfo>> {
            return ProductSpecificationApiFp(configuration).apiServicesAppProductSpecificationGetAllGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UpdateProductSpecificationDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppProductSpecificationUpdatePut(body?: UpdateProductSpecificationDto, options?: AxiosRequestConfig): Promise<AxiosResponse<ResultDto>> {
            return ProductSpecificationApiFp(configuration).apiServicesAppProductSpecificationUpdatePut(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProductSpecificationApi - object-oriented interface
 * @export
 * @class ProductSpecificationApi
 * @extends {BaseAPI}
 */
export class ProductSpecificationApi extends BaseAPI {
    /**
     * 
     * @param {AddProductSpecificationsDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductSpecificationApi
     */
    public async apiServicesAppProductSpecificationAddBulkPost(body?: AddProductSpecificationsDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<ResultDto>> {
        return ProductSpecificationApiFp(this.configuration).apiServicesAppProductSpecificationAddBulkPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {FilterProductSpecificationDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductSpecificationApi
     */
    public async apiServicesAppProductSpecificationFilterPost(body?: FilterProductSpecificationDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<ProductSpecificationsFilterResultInfo>> {
        return ProductSpecificationApiFp(this.configuration).apiServicesAppProductSpecificationFilterPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductSpecificationApi
     */
    public async apiServicesAppProductSpecificationGetAllGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<GetAllSpecificationsResultInfo>> {
        return ProductSpecificationApiFp(this.configuration).apiServicesAppProductSpecificationGetAllGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {UpdateProductSpecificationDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductSpecificationApi
     */
    public async apiServicesAppProductSpecificationUpdatePut(body?: UpdateProductSpecificationDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<ResultDto>> {
        return ProductSpecificationApiFp(this.configuration).apiServicesAppProductSpecificationUpdatePut(body, options).then((request) => request(this.axios, this.basePath));
    }
}
