/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AddResellerDto } from '../models';
import { ResellersSearchResultInfo } from '../models';
import { ResultDto } from '../models';
import { SearchResellerDto } from '../models';
import { ShowResellerResult } from '../models';
import { UpdateResellerDto } from '../models';
/**
 * ResellerApi - axios parameter creator
 * @export
 */
export const ResellerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {AddResellerDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServicesAppResellerAddPost: async (body?: AddResellerDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/services/app/Reseller/Add`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} resellerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServicesAppResellerDeleteDelete: async (resellerId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'resellerId' is not null or undefined
            if (resellerId === null || resellerId === undefined) {
                throw new RequiredError('resellerId','Required parameter resellerId was null or undefined when calling apiServicesAppResellerDeleteDelete.');
            }
            const localVarPath = `/api/services/app/Reseller/Delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (resellerId !== undefined) {
                localVarQueryParameter['ResellerId'] = resellerId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} resellerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServicesAppResellerGetByIdGet: async (resellerId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'resellerId' is not null or undefined
            if (resellerId === null || resellerId === undefined) {
                throw new RequiredError('resellerId','Required parameter resellerId was null or undefined when calling apiServicesAppResellerGetByIdGet.');
            }
            const localVarPath = `/api/services/app/Reseller/GetById`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (resellerId !== undefined) {
                localVarQueryParameter['ResellerId'] = resellerId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SearchResellerDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServicesAppResellerSearchPost: async (body?: SearchResellerDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/services/app/Reseller/Search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateResellerDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiServicesAppResellerUpdatePut: async (body?: UpdateResellerDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/services/app/Reseller/Update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ResellerApi - functional programming interface
 * @export
 */
export const ResellerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {AddResellerDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppResellerAddPost(body?: AddResellerDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ResultDto>>> {
            const localVarAxiosArgs = await ResellerApiAxiosParamCreator(configuration).apiServicesAppResellerAddPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {number} resellerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppResellerDeleteDelete(resellerId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ResultDto>>> {
            const localVarAxiosArgs = await ResellerApiAxiosParamCreator(configuration).apiServicesAppResellerDeleteDelete(resellerId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {number} resellerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppResellerGetByIdGet(resellerId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ShowResellerResult>>> {
            const localVarAxiosArgs = await ResellerApiAxiosParamCreator(configuration).apiServicesAppResellerGetByIdGet(resellerId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {SearchResellerDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppResellerSearchPost(body?: SearchResellerDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ResellersSearchResultInfo>>> {
            const localVarAxiosArgs = await ResellerApiAxiosParamCreator(configuration).apiServicesAppResellerSearchPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {UpdateResellerDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppResellerUpdatePut(body?: UpdateResellerDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ResultDto>>> {
            const localVarAxiosArgs = await ResellerApiAxiosParamCreator(configuration).apiServicesAppResellerUpdatePut(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ResellerApi - factory interface
 * @export
 */
export const ResellerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {AddResellerDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppResellerAddPost(body?: AddResellerDto, options?: AxiosRequestConfig): Promise<AxiosResponse<ResultDto>> {
            return ResellerApiFp(configuration).apiServicesAppResellerAddPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} resellerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppResellerDeleteDelete(resellerId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<ResultDto>> {
            return ResellerApiFp(configuration).apiServicesAppResellerDeleteDelete(resellerId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} resellerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppResellerGetByIdGet(resellerId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<ShowResellerResult>> {
            return ResellerApiFp(configuration).apiServicesAppResellerGetByIdGet(resellerId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SearchResellerDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppResellerSearchPost(body?: SearchResellerDto, options?: AxiosRequestConfig): Promise<AxiosResponse<ResellersSearchResultInfo>> {
            return ResellerApiFp(configuration).apiServicesAppResellerSearchPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UpdateResellerDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiServicesAppResellerUpdatePut(body?: UpdateResellerDto, options?: AxiosRequestConfig): Promise<AxiosResponse<ResultDto>> {
            return ResellerApiFp(configuration).apiServicesAppResellerUpdatePut(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ResellerApi - object-oriented interface
 * @export
 * @class ResellerApi
 * @extends {BaseAPI}
 */
export class ResellerApi extends BaseAPI {
    /**
     * 
     * @param {AddResellerDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResellerApi
     */
    public async apiServicesAppResellerAddPost(body?: AddResellerDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<ResultDto>> {
        return ResellerApiFp(this.configuration).apiServicesAppResellerAddPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {number} resellerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResellerApi
     */
    public async apiServicesAppResellerDeleteDelete(resellerId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<ResultDto>> {
        return ResellerApiFp(this.configuration).apiServicesAppResellerDeleteDelete(resellerId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {number} resellerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResellerApi
     */
    public async apiServicesAppResellerGetByIdGet(resellerId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<ShowResellerResult>> {
        return ResellerApiFp(this.configuration).apiServicesAppResellerGetByIdGet(resellerId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {SearchResellerDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResellerApi
     */
    public async apiServicesAppResellerSearchPost(body?: SearchResellerDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<ResellersSearchResultInfo>> {
        return ResellerApiFp(this.configuration).apiServicesAppResellerSearchPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {UpdateResellerDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResellerApi
     */
    public async apiServicesAppResellerUpdatePut(body?: UpdateResellerDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<ResultDto>> {
        return ResellerApiFp(this.configuration).apiServicesAppResellerUpdatePut(body, options).then((request) => request(this.axios, this.basePath));
    }
}
