/* tslint:disable */
/* eslint-disable */
/**
 * Digi-Mal-Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/brand-api';
export * from './apis/customer-api';
export * from './apis/factor-api';
export * from './apis/job-api';
export * from './apis/menu-api';
export * from './apis/multimedia-api';
export * from './apis/page-builder-api';
export * from './apis/product-api';
export * from './apis/product-and-property-price-api';
export * from './apis/product-property-api';
export * from './apis/product-specification-api';
export * from './apis/product-type-api';
export * from './apis/reseller-api';

